Pin "z3c.unconfigure" (fixes failing test setup).
This fixes an error during the buildout where "z3c.unconfigure" wants to install a newer version of "zope.configuration" causing a version conflict:

Error: The requirement ('zope.configuration>=3.8.0') is not allowed by your [versions] constraint (3.7.4)